sudo: false
dist: trusty
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
    - g++-mingw-w64-i686
install:
 - ./.ci/travis-prepare.sh
script:
 - ./.ci/travis-build.sh
env:
 - BRCORE=master
 - BRCORE=master CMPLR=clang
 - BRCORE=master USR_CXXFLAGS=-std=c++11
 - BRCORE=master USR_CXXFLAGS=-std=c++11 CMPLR=clang
 - BRCORE=master WINE=32 TEST=NO STATIC=YES
 - BRCORE=master WINE=32 TEST=NO STATIC=NO
 - BRCORE=master RTEMS=4.10 TEST=NO
 - BRCORE=master RTEMS=4.9 TEST=NO
